name: Trigger URL on Push or Merge to Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  triggerURL:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is merged
        if: github.event.pull_request.merged == true
        run: echo "PR was merged."
      - name: Get request to URL
        run: curl -X GET ${{ secrets.DEPLOY_URL_FOR_ASSIGNMENT_20240402 }}
        if: (github.event_name == 'push') || (github.event.pull_request.merged == true)
